### ISSUE TITLE
Illegal mime type for CMS upload of business rules

### ISSUE THREAD

**Issue by Razumain** [eu-digital-green-certificates/dgc-gateway#103]
## Describe the bug

The upload and delete API expects the mime type to be `application/cms-text`
All other upload and delete operation involving sending CMS data use the registered mime type `application/cms`

This creates problem when reusing common code for uploading and deleting data from the gateway.

## Expected behaviour

Use of the registered mime type `application/cms`

## Technical details

Another aspect of this is that also the registered mime type `application/cms` is also wrong since what is actually sent over the wire is not a binary CMS object, but a base64 encoded string holding a CSM object. Is this perhaps the reason why the new  `application/cms-text` mime type was invented?

I assume that a correct implementation would be to provide the binary CMS object with `application/cms` mime type. But there is no benefits at this point to change this at this stage. But the difference in implementation that is the case now is unfortunate and is likely to be the source of much confusion and implementation issues.

## Possible Fix

Ideally, to be as acceptable as possible I would propose the following:

1) For upload and deleting business rules accept both `application/cms` and  `application/cms-text`
2) For any upload and delete operation where you send CMS data to the gateway, accept both binary CMS object as well as a base64 encoded CMS object

**Comment by f11h** [comment]
The new Content-Type was introduced to be able to differ between signed certificates and signed strings (e.g. JSON).

But it turned out that it is not required to to such a separation on "Content-Type-Level" with PR #113 it is possible to use both Content-Types (application/cms-text and application/cms) for uploading and deleting Validation-Rules.
