### ISSUE TITLE
Where is this hosted?

### ISSUE THREAD

**Issue by panzi** [eu-digital-green-certificates/dgc-gateway#109]
## Your Question

I need to verify EHC QR-codes and for that I need the trust list, but I cannot find where this is hosted. Where can I download the trust list?

**Comment by daniel-eder** [comment]
The trust list is not published by the EU, rather each member state has control over who they give access to their solution. Please refer to https://github.com/eu-digital-green-certificates/dgc-participating-countries/issues/10 for the related discussion
