### ISSUE TITLE
Exception when uploading Business Rules without optional Field "Region"

### ISSUE THREAD

**Issue by chris-baumann-at** [eu-digital-green-certificates/dgc-gateway#116]
When trying to upload a rule (corresponding to https://github.com/eu-digital-green-certificates/dgc-gateway/blob/main/src/main/resources/validation-rule.schema.json) I receive the following Exception:

Caused by: eu.europa.ec.dgc.gateway.connector.DgcGatewayValidationRuleUploadConnector$DgcValidationRuleUploadException: Invalid JSON: JSON does not align to Validation Rule Schema: #/Region: expected type: String, found: Null

The rule does NOT include the field "Region", as it is not required.

**Comment by f11h** [comment]
Hi @chris-baumann-at ,
please check your serialized JSON.
The ```Region``` field is optional and it is possible to upload a rule WITHOUT the property. I guess you have set the value of Region to ```null``` which is not allowed. If the key is present it must be a string. If you do not want to set a region then do not include the key ```Region```.
