### ISSUE TITLE
Open API documentation does not match implementation

### ISSUE THREAD

**Issue by stamo** [eu-digital-green-certificates/dgc-gateway#117]
## Descripition

In the OpenApi documentation /rules/{country} endpoint returns an empty object on success, and the code generetor is generating void method. But the idea of this endpoint is to return bussiness rules for specific country.

```json

"/rules/{country}": {
    "get": {
        "tags": [
            "Validation Rules"
        ],
        "summary": "Download all rules of country.",
        "operationId": "downloadValidationRules",
        "parameters": [
            {
                "name": "country",
                "in": "path",
                "required": true,
                "schema": {
                    "type": "string"
                },
                "example": "EU"
            }
        ],
        "responses": {
            "200": {
                "description": "Download successful.",
                "content": {
                    "application/json": {}
                }
            }
        },
        "security": [
            {
                "Authentication Certificate Hash": []
            },
            {
                "Authentication Certificate Distinguish Name": []
            }
        ]
    }
}

```
I can replace this method with my implementation, but then next time I regenerate the client, I will have to reimplement it again. This can lead to certain regresion which is not the best case scenario.
 
## Expected behaviour

Provide OpenApi description of the return type of this endpoint, so the code generators would generate usable client.

## Steps to reproduce the issue

1. Go to **'https://eu-digital-green-certificates.github.io/dgc-gateway/openapi.json'**
2. Scroll down to **'/rules/{country}'**
3. In responses->200->content you will see **"application/json": {}**

## Technical details
I'm using
- NSwag Version: 13.11.1.0
- NJsonSchema Version: 10.4.3.0

[NSwag](https://github.com/RicoSuter/NSwag)

## Possible Fix

```json

"responses": {
            "200": {
                "description": "Download successful.",
                "content": {
                    "application/json": {
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "array",
                                "items": {
                                    "$ref": "#/components/schemas/DGCGResponseRuleModel"
                                }
                            }
                        }
                    }
                }
            }
        },

```
And the DGCGResponseRuleModel is

```json

"DGCGResponseRuleModel": {
    "type": "object",
    "properties": {
        "version": {
            "type": "string",
            "nullable": true
        },
        "validFrom": {
            "type": "string",
            "format": "date-time"
        },
        "validTo": {
            "type": "string",
            "format": "date-time"
        },
        "cms": {
            "type": "string",
            "nullable": true
        }
    },
    "additionalProperties": false
}

```

**Comment by stamo** [comment]
I don't like the asociative array that returns from this endpoint, but I assume that you have your considerations. It would be a lot more common if you used something like this

```json

[
    {
        "number": "GR-DX-0001",
        "version": "1.0.0",
        "validFrom": "2021-07-01T09:38:09+02:00",
        "validTo": "2021-07-06T09:38:09+02:00",
        "cms": "MIIL..."
    }
]

```

**Comment by f11h** [comment]
Hi @stamo ,

can you please check if this OpenAPI Spec fulfills your needs: [openapi.json.txt](https://github.com/eu-digital-green-certificates/dgc-gateway/files/6801007/openapi.json.txt)

**Comment by stamo** [comment]
Hi @f11h ,

Yes, thank you very much,  now the generated method has propper return type. 

Unfortunately I can not check all methods now, but "/rules/{country}" endpoint is OK, so I can close this issue

**Comment by f11h** [comment]
Cool - This change will be integrated in 1.1.4 and all further releases of the OpenAPI Spec will have this change included
