### ISSUE TITLE
Rule doesn't get automaticlly deleted

### ISSUE THREAD

**Issue by TKlauenberg** [eu-digital-green-certificates/dgc-gateway#118]
## Describe the bug

In ACC is a rule with the Attribute ValidTo on 2021/07/06. It should then be deleted but is still in the Rule Download.

## Expected behaviour

Rules with a value in the path for "ValidTo" should be automaticlly deleted.

## Technical details

ACC Environment

**Comment by f11h** [comment]
Deletion of rules was removed after some discussion.
--> GW Works as intended.
