### ISSUE TITLE
Clean install (for docker and local) fails when running tests.

### ISSUE THREAD

**Issue by boncossoftware** [eu-digital-green-certificates/dgc-gateway#120]
## Describe the bug
Build/Install is failing when running tests. 
 
## Expected behaviour
The tests should complete without issues.

## Steps to reproduce the issue
Run "mvn clean install -P docker" or "mvn clean install" from the terminal in the root dir. 

## Technical details
The tests are failing in "RatValuesetUpdateServiceTest.java" (see image for exact tests). 

##Host Machine OS and java version are:
On Mac OS X 10.15.7 with openjdk version "11.0.11" 2021-04-20, OpenJDK Runtime Environment AdoptOpenJDK-11.0.11+9 (build 11.0.11+9) and OpenJDK 64-Bit Server VM AdoptOpenJDK-11.0.11+9 (build 11.0.11+9, mixed mode). 

## Possible Fix
I will need to explore exactly what is being tested as I don't have the exact details yet.

**Comment by boncossoftware** [comment]
![Screen Shot 2021-07-14 at 09 19 21](https://user-images.githubusercontent.com/5249176/125631028-1bc72d89-228a-4daa-8bff-8dcff3dedf13.png)

**Comment by HammadUA** [comment]
Hi guys I have the same issue even though I am using the latest code available.

![Screenshot - 21_07_2021 , 10_32_12](https://user-images.githubusercontent.com/82023169/126467963-b26a2625-894f-40f2-832e-a6f10819a97b.jpg)

**Comment by boncossoftware** [comment]
> Hi guys I have the same issue even though I am using the latest code available.
> 
> ![Screenshot - 21_07_2021 , 10_32_12](https://user-images.githubusercontent.com/82023169/126467963-b26a2625-894f-40f2-832e-a6f10819a97b.jpg)

Are you also on mac?

**Comment by HammadUA** [comment]
@boncossoftware no I am using windows machine

**Comment by HammadUA** [comment]
@boncossoftware and @daniel-eder guys according to the tests error.log files all these 7 test failures are occurring due to non-matching timestamps issue. I hope this will help to solve the issue faster. Looking forward to hear. thanks

**Comment by f11h** [comment]
I will investigate on this - But I guess it will take some time

**Comment by HammadUA** [comment]
@f11h did you manage to fix the above issue ? Looking forward to hear from you. thanks

**Comment by f11h** [comment]
Sorry - I cannot reproduce your error. I've tested to build the gateway on two different systems and it works fine (both Windows 10 with AdoptJdk 11). I've tested both Docker and normal build.

**Comment by boncossoftware** [comment]
Could it be a java environment configuration issue? Timezone or something similar?

**Comment by hachembhl** [comment]
Hi,
I have the same issue on redhat environment!
can anyone help?
