### ISSUE TITLE
PKCS#7 responses lack length

### ISSUE THREAD

**Issue by dirkx** [eu-digital-green-certificates/dgc-gateway#124]
The PKCS#7 response of the gateway lack the length field (infinity is used):

        0:d=0  hl=2 l=inf  cons: SEQUENCE          
        2:d=1  hl=2 l=   9 prim: OBJECT            :pkcs7-signedData

It would be preferable to have this field be used as intended; e.g. with a length:

       0:d=0  hl=2 l=2519  cons: SEQUENCE          
       2:d=1  hl=2 l=   9 prim: OBJECT            :pkcs7-signedData

This makes the system more robust (e.g. it would have negated the impact of #125 ).

## Expected behaviour

Have a length defined.

## Steps to reproduce the issue

Pipe the signature/pkcs#7 to

      ... | base64 -d --ignore-missing-padding | openssl asn1parse -inform DER | head -6

and observe the occurance of 'inf'.

## Technical details

na

## Possible Fix

Set the length.

**Comment by f11h** [comment]
Hi @dirkx ,
at the moment we see no need for adding the length information as long as everything works fine without it. 
The effort to implement this would be much higher then the benefit.

Please reopen the ticket if you see a real problem in absence of the length value.

**Comment by dirkx** [comment]
Reason for this is that support for INF outside the world of Bouncy Castle Java is not that common. It is also security wise a bit risky.
