### ISSUE TITLE
Some PKCS#7 endpoint /trustList/{type}/{country} appear corrupted / have trailing 0's

### ISSUE THREAD

**Issue by dirkx** [eu-digital-green-certificates/dgc-gateway#125]
## Describe the bug

It appears that some KIDs (e.g. "hA1+pwEOxCI=", RO) have trailing 0's at the end of the record.

## Expected behaviour

The reply (signature) field be valid base64 and valid PKCS#7

## Steps to reproduce the issue

      kid": "hA1+pwEOxCI=",
         "timestamp": "2021-06-22T15:19:52+02:00",
         "country": "RO",
         "certificateType": "DSC",
         "thumbprint": "840d7ea7010ec4225055d242a35505db4a9cb63d26a7ec5533d3bfa168bb34dd",

has a signature turn:
    
`MIAGCSqGSIb3DQEHAqCAMIACAQExDzANBglghkgBZQMEAgEFADCABgkqhkiG9w0BBwEAAKCAMIIDUDCCATigAwIBAgIFFhg4Ix4wDQYJKoZIhvcNAQELBQAwTjELMAkGA1UEBhMCUk8xHTAbBgNVBAoMFE1pbmlzdGVydWwgU2FuYXRhdGlpMSAwHgYDVQQDDBdBQyBNaW5pc3RlcnVsIFNhbmF0YXRpaTAeFw0yMTA2MTgxMzMwMjVaFw0yNjA2MjIxMzMwMjVaMDwxCzAJBgNVBAYTAlJPMR0wGwYDVQQKDBRNaW5pc3RlcnVsIFNhbmF0YXRpaTEOMAwGA1UEAwwFTkItVVAwWTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAAQ7eBjBzVehCt3r7Fsck7F8un5W3nMyP1Q9EgxM3ZixZLv5bSsQEnZ9v8p2NRb/g12DCtTSB5s0C+Sd6tLsfg9OoxIwEDAOBgNVHQ8BAf8EBAMCB4AwDQYJKoZIhvcNAQELBQADggIBAFL/R0VcYYNG7gSF+7WI9cpaDSYEIjefEdOR5Hts42zN3Os4yizxpwBZg5YgaXG5edDsi2Q2pe5kF1bhGFqUfn1l92ekuVFKYZb5BjM5Vy3LhAdzOBVAwK3Jlu9Z9lr50bGzoyuMWT3P8P6HMw1hnh12PiqzwxlT4v+Qbgut5aAC7iHU3KHxvwSLCvCkuupjwFSTyWlnucA82mUf50vf79fw8eF32RVzUTXTseMJ/QtxTPw+YsGf9md0OWNeVly7VcYE9spNybob0r6199m4bMP7kN0/trfGyBeluQuxoZ4cLYFr+NVw+slFyUiRnrk6Qkt1GLpXVyHKYY/fXadXQLN92XhdtUL+WRohLRe5DspwuFKpSZCTvgpLGrZxCxfK/xvNMDhO1PC2vfGvQnSuyZIw7/rYpVtIaWWbF+rOy8gYdANmNBi83d0Z6wvTJu5HwKK/+CdIZWfFjunzVL8ZlLsr2znx64C6BvHWD2QZFyqhWepo1igSWuEx5bi2b5c3sLGeBucnjjmplidJEp0+eAPzO89vK1cWnxC0yLj/0sird9B7Jwp2T5sirEEuJ9MD9H1fThkhErrNnDIEwcZTdLmhgiPvgsHHxq/qu06jZvybUJ7IQRWckVgiWUqkyQwEpTBkB5GS9rPzKSYN7JuNnyH1jOCcblXcCn2slG1wmYPdAAAxggFcMIIBWAIBATBXME4xCzAJBgNVBAYTAlJPMR0wGwYDVQQKDBRNaW5pc3RlcnVsIFNhbmF0YXRpaTEgMB4GA1UEAwwXQUMgTWluaXN0ZXJ1bCBTYW5hdGF0aWkCBRYYOCMeMA0GCWCGSAFlAwQCAQUAoIGVMBgGCSqGSIb3DQEJAzELBgkqhkiG9w0BBwEwHAYJKoZIhvcNAQkFMQ8XDTIxMDYyMjEzMTk1MVowKgYJKoZIhvcNAQk0MR0wGzANBglghkgBZQMEAgEFAKEKBggqhkjOPQQDAjAvBgkqhkiG9w0BCQQxIgQghA1+pwEOxCJQVdJCo1UF20qctj0mp+xVM9O/oWi7NN0wCgYIKoZIzj0EAwIERzBFAiA03y7ZZVZTS1YLZYR43feav0+iKepkfImhU9g9+FZd+wIhAOKZynpUlVkOG+i2hW/IVaJK8WZ2FCZpmWyUuRx9NF8FAAAAAAAA
`
(no trailing line end; SHA256 - 0703733a08b7bd72d1bd0b0dceff32fb61695761771fdc3487db9b5016109518)

Firstly - the tail end of that base64 file:

    .....8FAAAAAAAA

looks odd. An ASN 1 decode:

	... | base64 -d --ignore-missing-padding | openssl asn1parse -inform DER

shows a some 0 length, 0 labeled fields at the end:

        2003:d=5  hl=4 l= 512 prim: OCTET STRING      [HEX DUMP]:CA98243D55AD....C269A8
        2519:d=3  hl=2 l=   0 prim: EOC               
        2521:d=2  hl=2 l=   0 prim: EOC  

So I guess the file should end with:

	.....8F=

to make this a valid PKCS#7 payload.  And this makes it the right length too.

## Technical details

na

## Possible Fix

prevent trailing 0's.

**Comment by dirkx** [comment]
On 5 Aug 2021, at 13:19, Felix Dittrich ***@***.***> wrote:
> I've tested the signature you have posted. Our DGC-Lib - which uses Bouncycastle under the hood - is able to parse and verify the signature. You are right that the 2 "Zero-Fields" at the and are not useful at all.
> 
And as this is against the standard - breaks some OpenSSL, .NET and Python native implementations.
> The effort to remove these two items is much higher than the potential benefit. We are using Bouncycastle to create these messages and "fixing" this would mean provide a fix in Boucnycastle or to parse the ASN1 message after creation and remove these bad entries. But of course the latter one would also introduce new possible source of err
> 

Well - in the end of the day you want to simply be "Strict in what you sent’  & Accommodating in what you receive (Postels Law)” - so making the DGC-Lib standards compliant would be wise.

I do not think it is needed to change Bouncycastle - simply check the length byte at the start - and remove any trailing cruft that is longer than that length and you are done. Which is a very ’safe’ thing to do.

Dw

**Comment by f11h** [comment]
Closing this issue because no proper solution is on hand and the issue did not rise any problems in last two years.
