### ISSUE TITLE
Trustlist contains data with wrong Base64 Padding

### ISSUE THREAD

**Issue by TKlauenberg** [eu-digital-green-certificates/dgc-gateway#126]
## Describe the bug

Some entries in the trustlist on ACC have a wrong padding. Examples are the certificates with the kid "+TQaHjAyzgA=", "aRNMAM2Em1A=" and "nUdNOnt+DJ4=".

## Expected behaviour

The padding of Base64 Entries in the trustlist should be correct.

**Comment by f11h** [comment]
Incorrect Padding was because of Onboarding Issues. Invalid entries are fixed.
