### ISSUE TITLE
Help me setup a reverse proxy https for DGCG local development

### ISSUE THREAD

**Issue by LonieN** [eu-digital-green-certificates/dgc-gateway#128]
I want to setup a reverse proxy https for DGCG to  make DGC_GATEWAY_CONNECTOR TLS

My local DGCG run on: http://localhost:8080/trustList
How to build DGC_GATEWAY_CONNECTOR_ENDPOINT=https://dgc-gateway.example.com

I tried my best with nginx or envoy but still cannot config success.

Is there anyone can help me with?
Hope & wait

Rgds,

**Comment by daniel-eder** [comment]
@f11h do we have any information on that?

**Comment by f11h** [comment]
You have to set up your NGINX to do Client Certificate Authentication. Your NGINX has to add 2 headers when forwarding the request: https://github.com/eu-digital-green-certificates/dgc-gateway#send-requests

**Comment by LonieN** [comment]
> You have to set up your NGINX to do Client Certificate Authentication. Your NGINX has to add 2 headers when forwarding the request: https://github.com/eu-digital-green-certificates/dgc-gateway#send-requests

Dear f11h,
Thanks for your reply, I have a final question, hope you help me:

- I had set up my NGINX to do Client Cer Authen for DGCG done, and check the connectivity with the following command:
  > curl -vvv -H "Accept: */*" --resolve dgc-gateway.example.com:443:192.168.0.25 --cert "cert_tls.pem" --key "key_tls.pem" https://dgc-gateway.example.com
And a output like:
![image](https://user-images.githubusercontent.com/30336860/131640659-a6f6dd64-6097-494f-9b62-6d15fd2a62b9.png)

- Next step in file (dgca-verifier-service\docker-compose.yml), I want to config:
  DGC_GATEWAY_CONNECTOR_TLSTRUSTSTORE_PATH=file:/ec/prod/app/san/dgc/tls_trust_store.p12
  DGC_GATEWAY_CONNECTOR_TLSKEYSTORE_PATH=file:/ec/prod/app/san/dgc/tls_key_store.p12

- I have a little confused in this, 3 files pub_tls.pem ,  tls.pem, tls_private.pem  from where?
![image](https://user-images.githubusercontent.com/30336860/131643972-bae7ac75-55b2-43d8-852c-2c7c4d4cade4.png)

- In case with my local DGCG, is 'tls_trust_store.p12' exported from 'cert_tls.pem'  And tls_key_store.p12 file from 'cert_tls.pem' & 'key_tls.pem'?

Rgds,
LonieN

**Comment by f11h** [comment]
Hi LonieN,

the Truststore has to contain the Server-Certificate of your Nginx.
The Keystore needs to contain the KeyPair which you have created in Gateway-First-Steps: https://github.com/eu-digital-green-certificates/dgc-gateway#start-local

**Comment by LonieN** [comment]
> Hi LonieN,
> 
> the Truststore has to contain the Server-Certificate of your Nginx.
> The Keystore needs to contain the KeyPair which you have created in Gateway-First-Steps: https://github.com/eu-digital-green-certificates/dgc-gateway#start-local

Dear f11h,

I have followed your instructions. I have created:
- tls_trust_store.p12 from server-cert of nginx (nginx_cert_tls.pem)
- tls_key_store.p12 from the KeyPair which I have created in Gateway-First-Steps (cert_ta.pem & key_ta.pem)

But when I rerun: docker-compose up. A output still error like:
  "
     Certificates download started
     Maximum age of cache reached. Fetching new TrustList from DGCG.
     Failed to Download certificates from DGC Gateway. Type: CSCA, status code: -1
     CSCA TrustStore contains 0 trusted certificates.
     Failed to Download certificates from DGC Gateway. Type: UPLOAD, status code: -1
     Upload TrustStore contains 0 trusted certificates.
     Fetching TrustList from DGCG
     Download of TrustListItems failed. DGCG responded with status code: -1
     DSC TrustStore contains 0 trusted certificates.
     Certificates download finished
  "

I don't know what I did wrong? 
The KeyPair which I have created in Gateway-First-Steps is TrustAnchor or Trusted Parties? 


Thanks so much
