### ISSUE TITLE
http://localhost:8080/trustList , when accessing it after deployment getting 404 not found error.

### ISSUE THREAD

**Issue by arunextasy** [eu-digital-green-certificates/dgc-gateway#130]
After deployment when accessing http://localhost:8080/trustList getting below error. Kindly help to resolve it.

C:\Users\VVSA\Downloads\curl-7.78.0_6-win64-mingw\curl-7.78.0-win64-mingw\bin>curl -X GET http://localhost:8080/trustList -H "accept: application/json" -H "X-SSL-Client-SHA256: 397da9eb17467a2b3b83704ab6490a540bef43e84f06a6bd885e6621572da401" -H "X-SSL-Client-DN: C=NL"
<!DOCTYPE html>
<html><head><title>Not Found</title></head>
<body>
<h2>Access Error: 404 -- Not Found</h2>
<pre>Cannot open document for: /trustList</pre>
</body>
</html>

**Comment by f11h** [comment]
Hi @arunextasy we are not able to reproduce your issue.

How did you start the gateway?
