### ISSUE TITLE
Normalize Casing

### ISSUE THREAD

**Issue by ubamrein** [eu-digital-green-certificates/dgc-gateway#133]
Currently there are three different casings used, each of which is enforced in various different ways. There should be a common casing, and/or case insensitive tests.

1) The JSON-Schema (https://github.com/eu-digital-green-certificates/dgc-gateway/blob/main/src/main/resources/validation-rule.schema.json) defines all JsonProperties as `PascalCase`

2) CertLogic-Rules are all `camelCased`

3) Enums or properties/keys in the JsonSchema for the gateway upload are either `PascalCased` (https://github.com/eu-digital-green-certificates/dgc-gateway/blob/9288e5e73c93307d6cf93b2a1e4d4469d6b378da/src/main/resources/validation-rule.schema.json#L33) or `SCREAMING_CASED` (https://github.com/eu-digital-green-certificates/dgc-certlogic-android/blob/30cf7282ee680e0a868f035e1d44aa4eb5b84e87/engine/src/main/java/dgca/verifier/app/engine/DefaultCertLogicEngine.kt#L96)

Since none of it is documented on one single page, it makes it nearly impossible to get it right... There should be one single casing throughout all schemas.

Further, the JsonSchema for gateway uploads should also verify the Engine to be `CERTLOGIC` (or whatever casing is used afterwards) since for the moment it is hardcoded anyways in the client engines, and is the only accepted value. Further, I suppose that is not expected to change in the near future.

**Comment by f11h** [comment]
Hello @ubamrein , I just implemented it as it was defined in the specification of the Rule-Engine. To change this we have to talk about this on a higher (architectural) level. Therefore I would close this issue at this place.

**Comment by ubamrein** [comment]
Could you link to the discussion here?
