### ISSUE TITLE
Do you provide API access to existing instance?

### ISSUE THREAD

**Issue by alex1815** [eu-digital-green-certificates/dgc-gateway#134]
## Your Question

Hello, I'm wondering if gateway can be access by third party backend and intergrated with an api key or another authorization mechanism? Or should we run it locally?
If has to be run locally can you advice which repositories we need for being able just to verify if certificate or test is valid or not and till when?

Thank you a lot for clarification. 

* Source File:
* Line(s):
* Question: Do you provide API access to existing instance?

**Comment by daniel-eder** [comment]
Hi @alex1815, the dcc gateway is not accessible directly by third party applications, it communicates only with national backends.
To verify/validate certificates, you need to interact with the national backends (specifically, the national backend of the country you are operating from). 

To this end, you need to contact your national health authority on how to interact with their backend.
See also https://github.com/eu-digital-green-certificates/dgc-participating-countries/issues/10 for further discussion on the topic.
