### ISSUE TITLE
Revocation batch sync

### ISSUE THREAD

**Issue by NamingException** [eu-digital-green-certificates/dgc-gateway#159]
Revocation batches are downloaded in chunks of 1000 based on changed column of tipe ZonedDateTime.

Currently the returned json contains the changed column in the ISO 8601 with offset format without milliseconds (2011-12-03T10:15:30+01:00). 

There is a low possibility that multiple batches have the same changed value and are found at the limit of the chunk
The 1000th and 1001st batch both have "changed" value 2011-12-03T10:15:30+01:00.

The first request would return 1000 batches but when we request the next chunk we would skip the 1001st batch.

**Comment by chrloch** [comment]
Mitigation is possible by update of the manual: 
To ensure that this edge case does not lead to dropped chunks, the client should subtract 1 second from the timestamp of the last entry and ignore the first entry of the 2nd batch (which is expected to be the same as the last entry of the 1st batch then)

**Comment by f11h** [comment]
API returns values as expected - To ensure complete downloads changes on client side are required.
