### ISSUE TITLE
[CMS Migration] GET /cms-migration delivers  raw DSC instead of CMS

### ISSUE THREAD

**Issue by chrloch** [eu-digital-green-certificates/dgc-gateway#163]
## Description

in the JSON delivered by GET /cms-migration

The "cms" attribute for entries of type "DSC" contains the raw DSC (base64 encoded DER) instead of the wrapping CMS

## Expected behaviour

"cms" attribute should contain CMS

**Comment by chrloch** [comment]
Reference: https://jira.apps.dev.otc.coronawarn.app/browse/TXR-6343

**Comment by chrloch** [comment]
Fix now delivers Signature without payload for DSC 
--> Should be unified behavior for DSC, REVOC, RULES in my opinion

**Comment by f11h** [comment]
Will be fixed with #171

**Comment by f11h** [comment]
Fix was megred and deployd - @chrloch can you please retest?

**Comment by chrloch** [comment]
Test successfull on TST environment
