### ISSUE TITLE
[CMS Migration] Do not show deleted entries in list of migratable entities

### ISSUE THREAD

**Issue by chrloch** [eu-digital-green-certificates/dgc-gateway#164]
## Current Implementation

GET /cms-migration 

returns a list of migratable items. The type and cms are shown for each item. 

Deleted revocation batches have a null/None value in the place of the "cms" and therefore cannot be migrated, as the migration will check that new_payload == old_payload.

## Suggested Enhancement

Deleted entries should not appear in the list of migratables

## Expected Benefits

Semantic coherence: Theses items are not migratable and therefore should not appear in the list of migratables.

**Comment by f11h** [comment]
fixed by #167
