### ISSUE TITLE
[DSC Delta Download] Short date format as defined by spec is not accepted

### ISSUE THREAD

**Issue by chrloch** [eu-digital-green-certificates/dgc-gateway#175]
## Description

The spec defines a short date format in the examples in the schema YYYYMMDD
When using it in a request, the application returns an HTTP 400 error

Test case reference TXR-6428

## Expected behaviour

The spec should only contain date formats which are accepted by the application

## Steps to reproduce the issue

curl https://gateway/trustList --cert mycert.pem --key mykey.pem -H 'If-Modified-Since: 20220226'

## Possible Fix

Remove short date format from spec.
Implementation is not suggested because this date format does not follow the relevant standards for this domain.

**Comment by chrloch** [comment]
Decision:
Fix documentation
Will not be implemented

**Comment by f11h** [comment]
The document that needs to be changed is not in the scope of this repository.
