### ISSUE TITLE
Test failing when building on the CLI

### ISSUE THREAD

**Issue by ryanbnl** [eu-digital-green-certificates/dgc-gateway#189]
Latest release (tag 1.3.14, #57488b3), the build fails here:

```
[ERROR] Failures:
[ERROR]   SignerInformationServiceTest.testSuccessfulGetSignerInformationIsSincePageable:101 expected: <7> but was: <3>
[INFO]
[ERROR] Tests run: 154, Failures: 1, Errors: 0, Skipped: 0
```

The test passes when executed in Intelli-J but not when ran via the CLI as per the instructions in the readme.

**Comment by f11h** [comment]
Hi @ryanbnl ,

the linked PR (#205 ) should fix your problem building the project.

**Comment by ryanbnl** [comment]
Thanks, I think I fixed the problem locally back then.
