### ISSUE TITLE
Upload certificate renewal process

### ISSUE THREAD

**Issue by fsirit** [eu-digital-green-certificates/dgc-gateway#201]
Hello,

My current Upload certificate is about to expire soon for my national backend. I have created my new upload certificate for renewal process and I will send it to EU. Before this renewal process do I have to revoke all dependent DSCs?  If I revoke these DSCs I will not able to verify old  DCCs that created by revoked DSCs. Is there any smooth process available for certificate changing without turning old DCCs invalid?

Regards.

**Comment by rschombu** [comment]
> 

Dear fsirit,
yes, there is available a smooth procedure so called CMS migration. please initiate the provision of new upload certificate to the EU. The Process will be triggered 1st to replace the existing certificate (being expired) and afterwards the DCCG Operation Team will get in contact with you regards to CMS migration. 
Normally few weeks before the cert expirated the DCCG Operation team is informing the known operational contacts from your country.
I hope this helps.
