### ISSUE TITLE
Logic part of rule is not validated correctly and sufficiently

### ISSUE THREAD

**Issue by dslmeinte** [eu-digital-green-certificates/dgc-gateway#209]
See: https://github.com/eu-digital-green-certificates/dgc-gateway/blob/298899edc0e78f98df204349173a13f74a7d334e/src/main/java/eu/europa/ec/dgc/gateway/service/ValidationRuleService.java#L392

The `Logic` field of a validation/business rule is only checked against a JSON Schema for the rule as a whole which doesn't know anything about CertLogic expressions. In particular, the schema demands that the expression be an object, but it could also validly be a boolean literal. (The schema for the `AffectedFields` also rules that out, because it demands there's at least one affected field corresponding to at least one `var` data access operation.)

Instead, the `Logic` field should be validated by CertLogic itself (through its `validateFormat` function), and optionally against the official CertLogic JSON Schema (as a sub schema): https://github.com/ehn-dcc-development/eu-dcc-business-rules/blob/main/certlogic/specification/schemas/CertLogic-expression.json

**Comment by f11h** [comment]
Hi @dslmeinte,
thanks for rising this issue - In general your point is right. But it was never a requirement for the gateway to check the logic content of the rules. At this point of the lifecycle of the gateway we will not add any new features, thats why I can only ask you to provide a PullRequest otherwise I would close this issue.

**Comment by dslmeinte** [comment]
OK to close. If it becomes relevant again I'm happy to provide a PR - provided issues like #216 are solved.

**Comment by f11h** [comment]
Thank you for your feedback.
