### ISSUE TITLE
Docker image does not work

### ISSUE THREAD

**Issue by ryanbnl** [eu-digital-green-certificates/dgc-gateway#216]
The supplied docker image does not work. It is based on Java 11 whilst the project has been updated to Java 17.

Also, the readme needs to be updated to install Java 17: I've already made a PR on the WHO fork (which has been accepted), I can port the changes here if you'd like?

**Comment by f11h** [comment]
Hi @ryanbnl,

a PR would be highly appreciated - Thanks in advance!
