### ISSUE TITLE
Implementating gateway locally

### ISSUE THREAD

**Issue by IvarsAkmentins** [eu-digital-green-certificates/dgc-gateway#26]
We are working on implementation of DGC in Latvia. While browsing repositories available on GitHub we are stuck on setting up DGCG locally. I hope you can help us clarify a few questions:

1. Is there any further information about the data needed for mysql tables (trusted_party and signer_information)? And any useful information on how do we create test certificates? We have looked in https://github.com/eu-digital-green-certificates/dgc-participating-countries but could not find information needed for the questions we have faced.
2.   What Thumbprint is used in the header (X-SSL-Client-SHA256) when sending request to DGCG? Should it be only SHA256 or additional format is also needed?

For now the fastest way to move forward would be providing information or example on what to put in mysql tables for testing and for endpoint header (X-SSL-Client-SHA256) value.

Thank you for response in advance.

**Comment by f11h** [comment]
Hi @IvarsAkmentins ,

The MySQL Tables will be created automatically by DGCG.
For testing you can use simple self signed certificates created with OpenSSL
```bash
openssl req -x509 -newkey rsa:4096 -keyout key.pem -out cert.pem -days 365
```

In addition you need a TrustAnchor for your system. A TrustAnchor can also be created by the OpenSSL command above. The trustanchor has to be imported in a Java Truststore:
```
keytool -importcert -keystore trustanchor.jks -storepass password -file your-created-trustanchor-cert.pem -alias trustanchor
```

Then in DGCG you have to set properties:
* ```dgc.trustAnchor.keyStorePath``` --> path of your created trustanchor.jks
* ```dgc.trustAnchor.certificateAlias``` --> trustanchor
* ```dgc.trustAnchor.keyStorePass``` --> password

The X-SSL-Client-SHA256 and X-SSL-Client-DN are used by DGCG to fulfil mutual TLS authentication. DGCG only accepts HTTP Requests. The LoadBalancer in Front of DGCG (not in this repository) does the mTLS termination and sets these headers. So to send requests you have to set the SHA-256 Hash of your Authentication certificate in the header and also put the Subject (e.g. C=EU) in the X-SSL-Client-DN header.

All Kinds of certificates need to explicitly whitelisted in trusted_party table. All entries in trusted_party table needs to be signed by your TrustAnchor. To Sign certificates you can use OpenSSL but I would recommend https://github.com/eu-digital-green-certificates/dgc-cli/blob/main/README.md
the dgc-cli provided methods to create TrustAnchor signatures for trusted_party certificates.

The full documentation and a detailed Step-by-Step HowTo is currently in creation.

**Comment by IvarsAkmentins** [comment]
Hi,

I got working locally. 
This issue https://github.com/eu-digital-green-certificates/dgc-cli/issues/4 helped me with certificates, if anyone needs reference to it.

Thank you for your help @f11h
