### ISSUE TITLE
feat: create endpoint /blacklist

### ISSUE THREAD

**Issue by ascheibal** [eu-digital-green-certificates/dgc-gateway#3]
## Feature description

create endpoints for POST, GET, DELETE

## Problem and motivation
- [ ] Gets the Blacklist information objects. (GET)
- [ ] Publishes Blacklist Information of a trusted Issuer. (POST)
- [ ] Revokes one Blacklist Information Object. (DELETE)

**Comment by f11h** [comment]
Out of scope.
