### ISSUE TITLE
Provide Postman Requests Files for DGCG

### ISSUE THREAD

**Issue by SchulzeStTSI** [eu-digital-green-certificates/dgc-gateway#31]
To support external testers, please provide the postman requests for the gateway.

**Comment by f11h** [comment]
Currently we are generating a OpenAPI.json file for each build. In my opinion it would be enough.
The PostmanCollection is a little bit diffucult to create automatically. Manually maintaining it would have the risk of drifting both apart :\

(Maybe this one would be a try: https://github.com/postmanlabs/openapi-to-postman)

**Comment by f11h** [comment]
This is a snapshot of current API:

[![Run in Postman](https://run.pstmn.io/button.svg)](https://app.getpostman.com/run-collection/d858816fb9b8cec9b943?action=collection%2Fimport)
