### ISSUE TITLE
Status Codes 403

### ISSUE THREAD

**Issue by TKlauenberg** [eu-digital-green-certificates/dgc-gateway#38]
## Status Code 403 on POST /signercertificate

When I upload a DSC certificate from another county I expect to get the http status code 403.
A detailed description is in the [API Test](https://github.com/eu-digital-green-certificates/dgc-api-tests/blob/main/specs/gateway/CreateCertificate.md#upload-dsc-with-mismatched-certificate)

The Error Code was 400

## Expected behaviour

The Error Code in the [specification of the EU](https://ec.europa.eu/health/sites/health/files/ehealth/docs/digital-green-certificates_v2_en.pdf) is that the error Code is 403.

**Comment by f11h** [comment]
As of the specification was not conform to HTTP RFC the status codes were changed in final implementation.
Please find the actual implementation attached to our latest release.
