### ISSUE TITLE
Status Code 406

### ISSUE THREAD

**Issue by TKlauenberg** [eu-digital-green-certificates/dgc-gateway#39]
## Status Code 406 on POST /signercertificate

When I upload a DSC certificate in the wrong format I should get the error code 406.
A detailed description is in the [API Test](https://github.com/eu-digital-green-certificates/dgc-api-tests/blob/main/specs/gateway/CreateCertificate.md#upload-dsc-in-a-wrong-format)

The Error Code was 400

## Expected behaviour

The Error Code in the [specification of the EU](https://ec.europa.eu/health/sites/health/files/ehealth/docs/digital-green-certificates_v2_en.pdf) is that the error Code is 406.

**Comment by f11h** [comment]
As of the specification was not conform to HTTP RFC the status codes were changed in final implementation.
Please find the actual implementation attached to our latest release.
