### ISSUE TITLE
Error Code 401 when building with Tomcat

### ISSUE THREAD

**Issue by MBruno001** [eu-digital-green-certificates/dgc-gateway#41]
We are working on the building process of the dgc-gateway in Malta and we are having trouble locating the username and password to put in the settings.xml. 

Could you kindly show us where the credentials can be located at?

![image](https://user-images.githubusercontent.com/82646367/117127435-5d7e6500-ad9c-11eb-88f5-742e527a8cdd.png)

Thank you in advance.

**Comment by karalgie** [comment]
Hi @MBruno001 ,

I am a developer from Lithuania and just went through all the steps necessary to build and run **dgc-gateway**. So maybe, I can be of help to you. :)

Currently, **dgc-gateway** has a dependency on `dgc-lib` (see [pom.xml](https://github.com/eu-digital-green-certificates/dgc-gateway/blob/1ba32146a87efc1a4c250918f6a3d780b293c573/pom.xml#L134)) that seems at this point in time to be only available on GitHub Packages registry.

Just like you mentioned you need to configure  Maven `.m2\settings.xml` to use GitHub Packages registry. You need to have a GitHub account for this. Generate and use your account personal access token ([Settings / Developer settings / Personal access tokens](https://github.com/settings/tokens)). This will allow you to use GitHub Packages registry. More information is available at [GitHub Docs - Working with the Apache Maven registry](https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-apache-maven-registry). This is an example how your Maven setting might look like:
```xml
  <activeProfiles>
    <activeProfile>github</activeProfile>
  </activeProfiles>

  <profiles>
    <profile>
      <id>github</id>
      <repositories>
        <repository>
          <id>central</id>
          <url>https://repo1.maven.org/maven2</url>
        </repository>
        <repository>
          <id>github</id>
          <url>https://maven.pkg.github.com/eu-digital-green-certificates/*</url>
          <snapshots>
            <enabled>true</enabled>
          </snapshots>
        </repository>
      </repositories>
    </profile>
  </profiles>

  <servers>
    <server>
      <id>github</id>
      <username> YOUR USERNAME </username>
      <password> YOUR PERSONAL ACCESS TOKEN </password>
    </server>
  </servers>
```

Alternatively, you can clone or download [dgc-lib](https://github.com/eu-digital-green-certificates/dgc-lib.git) directly from GitHub and build it yourself.

**Comment by daniel-eder** [comment]
> Hi @MBruno001 ,
> 
> I am a developer from Lithuania and just went through all the steps necessary to build and run **dgc-gateway**. So maybe, I can be of help to you. :)

Thanks a lot for sharing your steps - if I may add, it is very important that the personal access token / PAT includes the scope `read:packages`, otherwise the request will still fail.

**Comment by MBruno001** [comment]
Thank you very much both of you for your reply, we have managed to locate the credentials and successfully build the application.
