### ISSUE TITLE
Wrong Status Code with unauthorized Authentication certificate

### ISSUE THREAD

**Issue by TKlauenberg** [eu-digital-green-certificates/dgc-gateway#47]
## Description

When I try to upload/delete a DSC with an unauthorized certificate (not whitelisted) I get the http status code 403. I expected to get the status code 401.

## Steps to reproduce the issue

Execute scenario [Upload DSC with unauthorized client certificate](https://github.com/eu-digital-green-certificates/dgc-api-tests/blob/main/specs/gateway/CreateCertificate.md#upload-dsc-with-unauthorized-client-certificate) or [Delete DSC with unauthorized authentication](https://github.com/eu-digital-green-certificates/dgc-api-tests/blob/main/specs/gateway/DeleteCertificates.md#delete-a-dsc-with-unauthorized-authentication).

**Comment by f11h** [comment]
Bug is fixed with #46
