### ISSUE TITLE
Cannot download packages from repo

### ISSUE THREAD

**Issue by zeridon** [eu-digital-green-certificates/dgc-gateway#59]
## Describe the bug
During deployment we are unable to pull built packages

## Expected behaviour
Being able to pull packages

## Steps to reproduce the issue
* Open a package release (ex: https://github.com/eu-digital-green-certificates/dgc-gateway/packages/769273)
* copy command
* exec command (ex: `docker pull docker.pkg.github.com/eu-digital-green-certificates/dgc-gateway/container:1.0.1`

```
docker pull docker.pkg.github.com/eu-digital-green-certificates/dgc-gateway/container:1.0.1
Error response from daemon: Head https://docker.pkg.github.com/v2/eu-digital-green-certificates/dgc-gateway/container/manifests/1.0.1: no basic auth credentials
```

## Technical details

- Host Machine OS (Windows/Linux/Mac): linux

**Comment by f11h** [comment]
Hi @zeridon ,

you need to authenticate at GitHub Container Registry to download containers.

```
docker login docker.pkg.github.com/eu-digital-green-certificates
```

**Comment by zeridon** [comment]
Please update documentation to explicitly mention this. Users are not expected to be intricately familiar with non-public repos and the way to authenticate to them.

On the other hand as this is public code all instructions should be minimally available.

Can assist with PR if needed

**Comment by daniel-eder** [comment]
@zeridon Thank you, you are of course correct, we should make this as accessible as possible. A PR would be appreciated!

**Comment by f11h** [comment]
Thanks for your PR. I've merged it and I will close this issue.
