### ISSUE TITLE
[Question] Gateway Location?

### ISSUE THREAD

**Issue by psavva** [eu-digital-green-certificates/dgc-gateway#6]
Dear Team, 

Please can you confirm the following:
It is my understanding that the Gateway (DGCG), which is this repository (dgc-gateway) will only be installed in Brussels.
Can you confirm please.

If the above is true, can you please confirm what is the purpose of the "DGCG Connector Pod" within the K8s Deployment in Section 9 of the "20210330_DGCG_Architecture" document?

I would have assumed that the and the Certificate Issuing Service, and the Certificate Verification Service would connect to the DGC-Gateway by calling a known RESTFul endpoint on the gateway authenticated via X509 certificates via Https transport?  Hence, I do not understand the purpose of the "DGCG Connector Pod", unless the DBCG Connector Pod an instance of the DGC-Gateway which connects directly with the EU DGC-Gateway via Gateway to Gateway communications.
Please an you confirm this.

![image](https://user-images.githubusercontent.com/1454758/115023521-94f9a000-9ec7-11eb-8865-0edcb16222b7.png)

Best Regards
Panayiotis Savva
(Cyprus)

**Comment by SchulzeStTSI** [comment]
The DGCG Connector POD is a kind of service in this example which manages the Up and Download of Keys, TLS Authentication to the DGCG, CMS packaging, Trust Checks, PKD Connections etc. This can be in the deployment a seperate pod or a kind of software service inside of the backends. It's up to the developers what is more suitable for the own development/environment. But however it's implemented, the REST APIs of the DGCG are used.
