### ISSUE TITLE
Production DGC Gateway URL missing from the documentation

### ISSUE THREAD

**Issue by zajdee** [eu-digital-green-certificates/dgc-gateway#75]
Hi team,

on https://ec.europa.eu/commission/presscorner/detail/en/ip_21_2721 and https://ec.europa.eu/info/live-work-travel-eu/coronavirus-response/safe-covid-19-vaccines-europeans/eu-digital-covid-certificate_en#what-data-does-the-certificate-include-is-the-data-safe one can read that the production gateway is indeed live.

The API of the DGC Gateway is well documented on https://eu-digital-green-certificates.github.io/dgc-gateway/

There's however one crucial part missing in the API documentation - the gateway URL.

1. What is the gateway URL?
2. Can the URL please be added to the API documentation?

Thank you.

**Comment by f11h** [comment]
Hi @zajdee ,

We see no need in publishing the endpoint here in the documentation of the gateway.
The gateway is not intended to be used by "end users". Without any appropiate client certificates you would not get any response from the gateway. To download the certificates please ask your local government to gain access to your local infrastructure.

**Comment by zajdee** [comment]
Hi f11h,
I don't agree. The rest of the infrastructure is fairly open.
Whom to contact to get the access to the gateway?
I am unable to find a documented process how to request the client certificates for the gateway. Accessing just the local infrastructure does not really enable EU-wide DGC verification.

**Comment by SchulzeStTSI** [comment]
@zajdee The connection to the gateway is currently limited to national authorities and their representives. Please contact your national representive to align your use cases. They can provide you access to the data over the national infrastructure.

**Comment by zajdee** [comment]
Well, my primary use case is to retrieve the trust list (and the certificates to validate the data in the DGC). There should be no need to hide this specific API from the public. Also, my local government is highly unlikely to provide me with the trust list (and certificates) of the other countries.

**Comment by albydeca** [comment]
@zajdee have you been able to solve? I would benefit from access to the data verification keys too :)

**Comment by albydeca** [comment]
Any progress on this?

**Comment by daniel-eder** [comment]
Please see https://github.com/eu-digital-green-certificates/dgc-participating-countries/issues/10 for a discussion on this topic. 

The EU member states decided that the access to the trust list is in the authority of the member states, therefore the only official way to get access is through your national health authority.
