### ISSUE TITLE
Setup JSON Schema for Business Rules

### ISSUE THREAD

**Issue by SchulzeStTSI** [eu-digital-green-certificates/dgc-gateway#76]
Please create for the Business Rules Object (Rule name etc.) a JSON Schema and validate during the upload against it. (Schema Content Check)

The rule name should follow the pattern as defined in the rule identifiers OR any kind of guid. If the type is set to invalidation, any string is accepted.

Don't forget the country code, it was missed in the specification.

**Comment by f11h** [comment]
This Issue will be solved together with #77
