### ISSUE TITLE
Only newest Version of Rule is shown in download

### ISSUE THREAD

**Issue by TKlauenberg** [eu-digital-green-certificates/dgc-gateway#91]
## Only newest Version of Rule is shown in download

The rules I have used you can find here: [rules.zip](https://github.com/eu-digital-green-certificates/dgc-gateway/files/6725110/rules.zip)

The Rules are uploaded with the ID "VR-IE-0002". The response from the gateway can be found in this file: 
[IE.txt](https://github.com/eu-digital-green-certificates/dgc-gateway/files/6725129/IE.txt)

After I uploaded all rules (on 28.06.2021 so ValidFrom was always in the future), only the rule with the newest Version was shown in the Gateway.

## Expected behaviour

All created versions are shown in the download.

## Steps to reproduce the issue

1. Create a rule with multiple versions
2. Upload all Versions of the Rule
3. Download Rules of country
4. check if all versions are in the downloaded list

## Technical details

- TST environment

**Comment by f11h** [comment]
The linked PR (#92) provides a Unit-Test which confirms this finding.

**Comment by f11h** [comment]
Closed on behalf of #92
